ALTER SESSION SET CONTAINER = XEPDB1;

-- Create user
CREATE USER calendar_sync_user IDENTIFIED BY calendar_sync;

-- Grant necessary privileges
GRANT CONNECT, RESOURCE TO calendar_sync_user;

-- grant unlimited tablespace (or assign a specific tablespace)
GRANT UNLIMITED TABLESPACE TO calendar_sync_user;

-- Create calendar sync table
-- As calendar_sync_user
CREATE TABLE EVENTS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(255),
    DESCRIPTION VARCHAR2(1000),
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    TIMEZONE VARCHAR2(100),
    SYNCED_WITH_CALENDAR NUMBER(1) DEFAULT 0
);
